service: algo-trade-lambda
provider:
  name: aws
  region: eu-central-1
  runtime: python3.10

functions:
  cronHandler:
    handler: handler.algo_trade_start_function
    timeout: 900 # if not set, 6 by default. Max is 900
    events:
      # Invoke Lambda function every 10 minutes from 15:00 to 19:50 (UTC) on weekdays
      # TODO Think about a different schedule based on legal hour change (maybe two rules?) Also think about holidays
      - schedule: cron(0/10 15-19 ? * MON-FRI *)
    environment:
      ALPACA_API_KEY: ${env:ALPACA_API_KEY}
      ALPACA_SECRET_KEY: ${env:ALPACA_SECRET_KEY}
      FINANCIAL_MODELING_API_KEY: ${env:FINANCIAL_MODELING_API_KEY}
      MULTIPLIER: ${env:MULTIPLIER}
      SNS_TOPIC_ARN: ${env:SNS_TOPIC_ARN}
plugins:
  - serverless-python-requirements
