service: algo-trade-lambda
provider:
  name: aws
  region: eu-central-1
  runtime: python3.10

functions:
  cronHandler:
    handler: handler.algo_trade_start_function
    events:
      # Invoke Lambda function evert 10 minutes from 10:00 to 14:50 on weekdays
      - schedule: cron(0/10 15-21 ? * MON-FRI *)
    
plugins:
  - serverless-python-requirements
